<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.3 setup script
 * Date: Sat, 14 Jun 2014 18:43:51 -0500
 */

/* Servers configuration */
$i = 0;

/* Server: Hermes [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Hermes';
$cfg['Servers'][$i]['host'] = '10.151.1.10';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Ftw3nt3rtainm3ntOnHermes';

/* End of servers configuration */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ForceSSL'] = true;
$cfg['blowfish_secret'] = '539cdd9e4e6d13.35279573';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
